name: GCP Deployment

on:
 workflow_dispatch:
    # branches:
    #   - main  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
      
         
      - name: Authenticate with Google Cloud
        with:
         project_id: ${{ secrets.GCP_PROJECT_ID }}
         service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
         export_default_credentials: true
         

      - name: Deploy GCP Module
        run: |
          terraform init
          terraform plan
        # env:
        #   GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # You can store your GCP project ID as a secret in GitHub

